// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrtzugagaaxcqceozcrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndydHp1Z2FnYWF4Y3FjZW96Y3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDUzMjksImV4cCI6MjA2NzI4MTMyOX0.qANh2CDoq1W12e820nZwQc8pHxKpM3x6DgfTCYajFuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});